version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: linkuni-postgres
    environment:
      POSTGRES_DB: linkuni-db
      POSTGRES_USER: chhavikantmahobia
      POSTGRES_PASSWORD: chhavikantmahobia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chhavikantmahobia -d linkuni-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: linkuni-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB_NAME: linkuni-db
      ADMINER_DEFAULT_USER: chhavikantmahobia

  backend:
    build: .
    container_name: linkuni-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linkuni-db
      SPRING_DATASOURCE_USERNAME: chhavikantmahobia
      SPRING_DATASOURCE_PASSWORD: chhavikantmahobia
      # Flask service configuration
      APP_FLASK_BASE_URL: http://host.docker.internal:5000
      # Other properties can be overridden here
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_FRONTEND_URL: http://localhost:3000
      APP_COOKIE_SECURE: "false"

volumes:
  postgres_data: 